# Generated by CMake 2.8.9

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target generate_codebook
ADD_EXECUTABLE(generate_codebook IMPORTED)

# Create imported target genlspdtcb
ADD_EXECUTABLE(genlspdtcb IMPORTED)

# Import target "generate_codebook" for configuration "Debug"
SET_PROPERTY(TARGET generate_codebook APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(generate_codebook PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pi/dev/secure_modem/workshop/audio_c2/codec2-master/build_linux/src/generate_codebook"
  )

# Import target "genlspdtcb" for configuration "Debug"
SET_PROPERTY(TARGET genlspdtcb APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(genlspdtcb PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pi/dev/secure_modem/workshop/audio_c2/codec2-master/build_linux/src/genlspdtcb"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
