#*****************************************************************************
#* DVSI CONFIDENTIAL PROPRIETARY 
#******************************************************************************
#* DVSI AMBE+2^(TM) Speech Coder
#* (c) Copyright, Digital Voice Systems Inc., 2002
#* All Rights Reserved
#*
#* DVSI claims certain rights, including patent rights under
#* U.S. Patents #5,226,084, #5,247,579, #5,491,772, #5,517,511 
#* and under other U.S. and foreign patents pending, in the 
#* AMBE+2^(TM) speech coding technology embodied in this software.  
#* Any use of this software or technology requires a separate 
#* written license from DVSI.
#* 	
#* AMBE is a trademark of Digital Voice Systems, Inc.
#******************************************************************************
#* $Name:  $
#* $RCSfile: Makefile,v $
#* $Revision: 1.1 $
#* $Date: 2008/08/05 20:10:48 $
#*****************************************************************************

default:
	cl *.c *.cpp -Fehdkcom.exe
